### ISSUE TITLE
More convinient anisotropy analysis of vv and vh decays

### ISSUE THREAD

**Issue by mpopara** [Fluorescence-Tools/chisurf#44] opened 2020-10-06 17:23 UTC
I have experienced that when one fits vv and vh decays with purpose of getting depolarization times and their amplitudes, one can get very good fit of vv and vh decays, but when these model vv and vh decays are combined into anisotropy, it does not necessarily fit into raw anisotropy decay.
After first fit iteration, user has to export model decays, combine them into anisotropy, and see how it fits into actual anisotropy decay. I experienced that often it misfits in the maximum (where r0 and g-factor contribute the most). Then, additional interation is needed to try to improve the fit. Again-export model decays, combine them, check how it fits.
It would be great if there would be a feature that combines vv and vh model decays, and overlays it with raw anisotropy, as additional fit quality check.

**Comment by tpeulen** [comment] 2020-10-06 22:47
"it does not necessarily fit into raw anisotropy decay." This is actually very expected behavior. You will only get the "correct" anisotropy if you compute r(t) with ideal decays, i.e., no scatter, no time-shifts. Experimental r(t) computed by (VV-VH)/(VV+G*2VH) will differ from what you expect, mainly because of time-shifts and scatter.

Another problem (in ChiSurf) is that the decays are scaled individually be default. If you want global scaling (a single scaling number for both decays) you have to disable the autoscale option, link number that scales the decays. The number that scales the decays is labeled "n0". If you "unfix" n0 the autoscaling is disabled and you can scale both decays in a global fit.

I think this answer should already solve you issue. However, I will leave this issue open, as I understand that more convinient global analysis of anisotropies is useful.

**Comment by tpeulen** [comment] 2024-10-10 08:19
That issue should be resolved with the anisotropy wizard that will be introduced in the next release as a plugin.
See:
https://github.com/Fluorescence-Tools/chisurf/tree/development/chisurf/plugins/anisotropy

**Closed by tpeulen** 2024-10-10 08:19 UTC
